### ISSUE TITLE
2418. Sort the People

### ISSUE THREAD

**Issue by saritapatel8770** [saritapatel8770/Leetcode-solutions#22]
Link - https://leetcode.com/problems/sort-the-people/

**Comment by ghost** [comment]
@saritapatel8770 I want to solve this problem
could you assign me

**Comment by ghost** [comment]
@saritapatel8770 hey, solved this

**Comment by ghost** [comment]
Hey @saritapatel8770 
I solved this problem but when I was trying to access map's element then it was giving me an compiler error so I used different method. But could you tell me what was wrong in this?

the error was : 
Line 10: Char 33: error: no member named 'second' in 'std::__cxx11::basic_string<char>'
            ans.push_back(mp[i].second);
                          ~~~~~ ^
1 error generated.

The code was : 
        map<int, string> mp;
        for(int i=0;i<names.size();i++){
            mp[heights[i]]= names[i];
        }
        vector<string> ans;
       for(int i=names.size()-1;i>=0;i--){
            ans.push_back(mp[i].second);  // here it is giving error 
        
        }
        return ans;        
    }
};

**Comment by ghost** [comment]
@saritapatel8770 was my PR successfully merged? or it's invalid.. why so?

**Comment by ghost** [comment]
Okay, got it
I push empty file .. I forgot to save the file in vs code that's why this has happed .. could you give me another chaance

**Comment by ghost** [comment]
hey could you check my PR now
